### ISSUE TITLE
Click the hyperlink text as opposed to clicking the icon

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#11]
Suggested by https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/reviews/409340/

Add an option to also be able to click on the hyperlink itself instead of the icon added by the addon.

**Comment by AWolf81** [comment]
Should work now with latest master after PR #50 and I think we can close this.

**Comment by piyushsoni** [comment]
Awesome! Any idea when will it be available in the AMO?

**Comment by feinstaub** [comment]
The addon has just been put to the AMO review process. Thanks to @AWolf81 the addon received a major rewrite which increases stability and maintainability. But it is hard to say when the review is actually complete. Maybe there will be additional findings. Let's hope for the best. :)

**Comment by feinstaub** [comment]
The review has been completed, 0.99.42 should be available now from https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/
