### ISSUE TITLE
Add a prefix option

### ISSUE THREAD

**Issue by PieterBreugelmans** [feinstaub/firefox_addon_local_filesystem_links#12]
My use case scenario is repetitive in such a way that my 'case files' are stored in individual directories, identified by their case ID which is listed on a web UI. A prefix option would allow a user to select the case ID, and have the add-on automatically add eg. C:\MyCaseFile\ as prefix to the select case ID (eg. 1234A), opening the C:\MyCaseFile\1234A directory in Windows Explorer.

**Comment by feinstaub** [comment]
I will close old bugs. Is this still an issue? If yes please don't hesitate to reopen it.
