### ISSUE TITLE
Problem in enable addon

### ISSUE THREAD

**Issue by ksypolit** [feinstaub/firefox_addon_local_filesystem_links#17]
Hello, i want to use the addon in a intranet application that holds links to local files and paths.

When i installed the addon in a machine with Windows Server 2003 (Standard Edition) with Firefox 23.0.1 (English Version) it works OK.

When i installed the addon in a machine with Windows Server 2008 (Enterprise Edition) with Firefox 23.0.1 (English Version) it doesn't work. When i go to the addon page in Firefox i see that Local FileSystem Links is installed but it doesn't appear in the add-on bar neither it works in the pages of my php application (the folder icon doesn't appear).

I already uninstall and reinstall the plugin and the Firefox, but no luck. Do you have any idea where to look for more info or how to fix that issue.

**Comment by feinstaub** [comment]
Closed for now, please reopen when needed.
