### ISSUE TITLE
Display of if page is being ignored by user setting is buggy

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#19]
see TODO

**Comment by AWolf81** [comment]
I think we can close this. If it is still an issue please re-open it. 

Because whitelisting is working. No icon and no link on not whitelisted pages. Only modifying of whitelist with active whitelisted tab could be improved. Removing a whitelisted page requires a page reload.

**Comment by feinstaub** [comment]
> Removing a whitelisted page requires a page reload.

I can confirm that.

Closing this issue is ok.

Nice to have though would be a way to see or check if a particular page has hyperlink scanning enabled or not.
