### ISSUE TITLE
Multiple icons at each edit.

### ISSUE THREAD

**Issue by alexbuisson** [feinstaub/firefox_addon_local_filesystem_links#20]
Hi,
I forked your code several month ago to fix a issue and today due to an automatic update It came back :) So I'm wondering if you can have a look at what I made in : https://github.com/alexbuisson/firefox_addon_local_filesystem_links

In fact I use often your extension when I create page under a company based CMS. And each time I edit a web page where a local link already exist it include/add the nice folder icon ! After 5 edit I came to 5 icon for each local link ....

I fixed that issue in the fork, you may want to merge those change into the master ... Let me know !!!!

**Comment by sweoggy** [comment]
Is this error still present in the current version? I might have fixed it while adding support for DOM changes.

**Comment by feinstaub** [comment]
There was no feedback for more than a year. I'll close the issue.
