### ISSUE TITLE
windows variables

### ISSUE THREAD

**Issue by Jonnyooo** [feinstaub/firefox_addon_local_filesystem_links#22]
Hi,

how about adding support for windows variables like:
file:///%localappdata%
?

Other than that, I really like your addon! Thank you so much!

**Comment by AWolf81** [comment]
@Jonnyooo I also like the proposed idea that why I've added this feature.
 
So pretty old request but now it is implemented (see PR #73.)
It will be added in a future release of the addon.

**Comment by AWolf81** [comment]
This is now implemented in version 0.99.46.

But please notice that there is a problem with encoding. So it's recommended to add the % inside links with %25 and for Linux $ use %24.

In 0.99.46 it is working with % and $ in your link but this behaviour will change with the next version. Until we've found a better solution.
