### ISSUE TITLE
Automatically react on DOM changes

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#24]
Background:
- https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/1
- https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/1#issuecomment-40004097

Possible solution on how to efficiently react do DOM changes that are caused for example by AJAX request:

- https://hacks.mozilla.org/2012/05/dom-mutationobserver-reacting-to-dom-changes-without-killing-browser-performance/
- https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by hakakou** [comment]
Because opening file explorer using the a file:// url would be extremely helpful for my project. I could have all my users install this extension. So I would like to ask: 

Would it be possible for my javascript code on my web project to manually call the rescan button on your extension after each ajax request? 

This I would like to do until you are able to fix this issue with reacting to DOM changes. Thanks!

**Comment by feinstaub** [comment]
Good question. I currently don't know if it is possible to interact with the addin's javascript. I did a quick check with the Firefox Debugger but I could not find the addin's source. But maybe I did not look at the right place...

**Comment by Chris78** [comment]
Hi there,

as I could see you are using jQuery in your addon. So couldn't you listen for mouseover events of a-tags on the body element and append the explorer icon to the a-tag (if not already present)? All a-tag events bubble up to the body, no matter if the a-tag is initially loaded or load via ajax.
This way the addon would automatically support content that is loaded via Ajax, Pjax etc.. 

I don't know much about addon development but that's the way you could do it in a web application. 

Regards
Chris

PS: We really like your addon and I hope I could help out a little. Looking forward to the next version of it :)

**Comment by Chris78** [comment]
Hi again, 

I also did a quick search on possibilities of interaction between the page's javascript context and the addon's javascript context. As far as I read, in general this is not possible because of security reasons (addons/XUL are very mighty tools!). But, there seems to be the possibility that the addOn provides an API, that can be used by the page's javascript. So the API could provide a public rescan function to the page's js context. Still some more research needed to point out how to actually do it...

Regards 
Chris

**Comment by feinstaub** [comment]
Hi Chris,
thanks for the input and research! As soon as I work again on the addin I'll see what can be done.

**Comment by sweoggy** [comment]
I have done some initial work on this in my fork. It uses MutationObserver. I see no real performance hit. https://github.com/sweoggy/firefox_addon_local_filesystem_links/commit/95ec75ba30d9bfc81db0d1f5ab8e671e9e08d492

**Comment by feinstaub** [comment]
@sweoggy: thanks for the input. I moved some of the commits of your branch into master branch. Then I applied 95ec75ba30d9bfc81db0d1f5ab8e671e9e08d492. When using the test server on http://127.0.0.1:8125/issue1/issue.htm, I got this:

![configure menu dialog1](https://cloud.githubusercontent.com/assets/368412/8511781/bfe722f2-2325-11e5-8be1-039bc7fad758.png)

(two folder icons instead of one)

When hitting the "Add link" button a few times, this:

![configure menu dialog1](https://cloud.githubusercontent.com/assets/368412/8511775/78feec4e-2325-11e5-93ee-a9b8388fe573.png)

So, it's not working for me.

Could you try to reproduce your code on latest master and with the above mentioned test case?

**Comment by MurzNN** [comment]
Maybe you can add JS listener for detect DOM changes? I do something like this in https://github.com/Qseo/QSEO-tools-Yandex/blob/master/QSEO-tools-Yandex/QSEO-tools-Yandex.user.js script, here is the code:
$('.main__center-inner').get(0).addEventListener('DOMNodeInserted', qseoToolsParse, false); 

So you can add something like:
$('body').get(0).addEventListener('DOMNodeInserted', recheckLocalLinks, false);

**Comment by sweoggy** [comment]
@feinstaub The double folder icon is a bug, I will try to fix that tomorrow. I will also take a look at the test case tomorrow and @MurzNN solution :)

**Comment by feinstaub** [comment]
By the way, do encounter a problem like this one https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/34? I am currently not able to run the unit tests.

**Comment by sweoggy** [comment]
@feinstaub  The test page doesn't work because it adds a LI tag with an A tag as innerHTML. My local page works because it adds an actual A tag :

var a = document.createElement("a");
a.className = "black";
a.setAttribute("href",link);
a.innerHTML = title;

**Comment by sweoggy** [comment]
I have fixed the test case as of https://github.com/sweoggy/firefox_addon_local_filesystem_links/commit/e95d8da1629194aa29eba91031c69a7efdcdbd8f and the double icon bug

**Comment by feinstaub** [comment]
implemented in v0.99.38

**Comment by feinstaub** [comment]
I will close old bugs. Is this still an issue? If yes please don't hesitate to reopen it.
