### ISSUE TITLE
Breaks Fastmail.fm

### ISSUE THREAD

**Issue by adipose** [feinstaub/firefox_addon_local_filesystem_links#26]
For some reason, with this enabled, I cannot load/read any e-mail in Fastmail.fm.  After disabling it, it works fine.

I have to reload Fastmail to get my inbox back, but once I click on an e-mail, nothing works again.

**Comment by feinstaub** [comment]
I will close old bugs. Is this still an issue? If yes please don't hesitate to reopen it.
