### ISSUE TITLE
Local file System addon is not working for Firefox version 30.0

### ISSUE THREAD

**Issue by cxtecny** [feinstaub/firefox_addon_local_filesystem_links#28]
Add on is perfectly working for Firefox version 21.0.  But when we have updated Firefox from 21.0 to 30.0 it has stopped working. I am unable to see folder icon, which is used to link to the network folder.

I have a network link for which I use this add on. 
This is how I have my link set up:   file://///server_name/file_name

That's how it looks with Firefox with version 21.0
![image2](https://cloud.githubusercontent.com/assets/8150819/3565104/b9b085ea-0aa8-11e4-94e0-379ec7b58f07.PNG)

With Firefox version 30.0 (no icon)
![image1](https://cloud.githubusercontent.com/assets/8150819/3565124/9ed7566c-0aa9-11e4-966d-2ac9c94b88dc.PNG)

Thanks in advance.

Kajal

**Comment by feinstaub** [comment]
Hi, sorry for getting to you so late. I currently work with FF 35. Is it still not working for you? Did you try to press the "Rescan" button?

**Comment by feinstaub** [comment]
any update on this?

**Comment by feinstaub** [comment]
I close it now, please reopen when it is still an issue.
