### ISSUE TITLE
open windows shares from linux host

### ISSUE THREAD

**Issue by icecom3** [feinstaub/firefox_addon_local_filesystem_links#29]
I love this addon, however from a linux machine the os converts the windows share file stucture from...
this=   file://///share/filename.pdf 
to this=   file:///\share\filename.pdf

So it does not open when viewing a windows share from a linux host (I am using ubuntu)

Is there any way this addon could be updated to compensate?  Or if anyone has any other ideas that would be great :)

Thanks in advance!

**Comment by feinstaub** [comment]
Thanks for the report. Can you please clarify the issue because normally backslashes (\) will be converted to slashes (/) by Firefox. Your report reads like it is the other way round.

**Comment by icecom3** [comment]
Sorry for late reply.  This is the way it converts when using mozilla+Addon on Ubuntu and accessing a link on a webpage that references a file system on the network. 

We have a share on the network, and an HTML page that links to the files in the share.  It works fine in windows, and the local file system links addon works fine also.  However in Linux it seems it fails.  In windows it reads " file://///share/filename.pdf " which will work, but in Linux it reads " file:///\share\filename.pdf" and fails.  I don't think the issue is the addon, but I guess I was hoping there was a way the addon could course correct that weird change that is making it fail in Ubuntu.

**Comment by feinstaub** [comment]
I wonder why there are backslashes in the URL. Can you extend to the test suite page test/webserver/std1/issue.htm to reproduce the behaviour?

**Comment by icecom3** [comment]
Sorry for the late reply.  Not sure what you mean by extend to the test suit page.  

The reason why there are back slashes is because in windows networking the explorer uses them.  They are hard coded in the links on the local intranet page.  

So I think windows web browsers are converting the network path of \\server\folder\ to file://server/folder, but linux tries to open them as is and fails.  I was hoping an addon might help.  but what I end up with is an error from Local Filesystem Links that says Sorry, The following path could not be found: file:///\\server\folder   

is there anyway to put in code an option to convert all back slashes to forward?

**Comment by feinstaub** [comment]
This might be related with https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/57

**Comment by feinstaub** [comment]
Is this still an issue? Then please re-open.
