### ISSUE TITLE
Add support for Linux file links like file:///home/user/file1.txt

### ISSUE THREAD

**Issue by MurzNN** [feinstaub/firefox_addon_local_filesystem_links#31]
I install your extension on Ubuntu Linux and it not work with linux link types like  file:///home/user/file1.txt
If I open them directly from url bar - it opens normally, but via extension Icon I see error:
Sorry. The following path could not be found:
file:///home/user/file1.txt

Can you fix this problem?

**Comment by icecom3** [comment]
I have same problem, but it happens to me when I open files over a local area network on Ubuntu.

**Comment by feinstaub** [comment]
Thanks for the report. I can confirm this also. It's a bug.

**Comment by icecom3** [comment]
I would be willing to make a small donation to get this fixed 😊

**Comment by feinstaub** [comment]
Wish granted with 23be8146e13c7f49d5fbdbef267479e41378251c. I hope you donated. ;-)

**Comment by feinstaub** [comment]
see also https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/13

**Comment by MurzNN** [comment]
Thanks for fixing, I donate too :)
