### ISSUE TITLE
Have both: "Open containing folder" and "Open file"

### ISSUE THREAD

**Issue by MurzNN** [feinstaub/firefox_addon_local_filesystem_links#32]
Very often I want to open folder, that containing file, not the file. Will be good optionally add menuitem "Open containing folder" that opens folder which file are located.

**Comment by feinstaub** [comment]
Open containing folder is the current behaviour of v0.99.25. Do you observe it otherwise?

**Comment by MurzNN** [comment]
I can't find the way how to open folder: At not there are version 0.99.37, I see icon near the link, on click I can open file, but I see no way to open containing folder in the right click menu or in other places. Here is screenshot: http://i.imgur.com/0z60SAR.png
Can you provide screenshot with example of "Open containing folder" functional?

**Comment by Torbo** [comment]
We use this plugin so that our employees can open the folder where a linked file exists in file explorer instead of launching the file.  That was the preferred action, now with the latest update there is no way to go back.  Help?!

**Comment by feinstaub** [comment]
@MurzNN, @Torbo: version 0.99.37 is broken.

As a quick fix please go down the addon's page and expand the "Version information" section. There, click "See complete version history". Hover over "Version 0.99.25.1-signed" and click "Add to Firefox". This will install the previous version. Direct link: https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/versions/?page=1#version-0.99.25.1-signed

**Comment by feinstaub** [comment]
Further discussions of how to fix it, see https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/37

**Comment by feinstaub** [comment]
On the original thread topic: The plan is provide both ways. Currently, if the users clicks the folder icon the file containing folder is opened. The idea is to instead open a drop down menu with two items:
- Open containing folder
- Open with default application

**Comment by Torbo** [comment]
Thanks guys rolling back to the previous version will work for us.

PS this has been a VERY useful Add-On we love it very much, thank you for making it.

I almost tried to figure out how to make my own fork of this to turn back on the previous method of opening the folder.  I like the idea of having the option to do either, we currently have that option; if the user clicks the link they open the file, if they click the folder they get "the folder" where the file exists.
Now if I could just get this to work on MAC I will be in business...

**Comment by feinstaub** [comment]
Since https://github.com/feinstaub/firefox_addon_local_filesystem_links/pull/50 (version 0.99.42, not available at AMO yet) there will be a context menu item "Link addon - Reveal selected link".

**Comment by AWolf81** [comment]
I think it would be better to have the reveal option also at the icon (as in issue #44). I would also keep the reveal in the context menu so both can be used.

I'll check if we can attach a click handler to the icon that opens the containing folder. That should be easy to implement.

What do you think? Should I add this?

**Comment by feinstaub** [comment]
@AWolf81: yes, I this on my mind, too! Thanks for bringing this up.

>  I would also keep the reveal in the context menu so both can be used.

The context menu should always contain all available options. In case we have only one icon, the menu item which corresponds to the icon action could have a " (default)" postfix to its label.

> I think it would be better to have the reveal option also at the icon

You mean two icons? I think two icons would be a bit of a UI overload. But one could try to implement a dropdown or something similar which can be interacted with using the left mouse button only.

About default actions with respect to https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/16, I would propose the following:
- For files the default action should be "reveal" (should be changeable in the addon settings since many users seem to like it the other way)
- For folders the default action should be "open"

Side note: Instead of the term "reveal" I would use the more common "Open containing folder".

**Comment by AWolf81** [comment]
No, my ideas is to have just one icon to open containing folder on click and click on the link text will open the file.

You're right "reveal" can be confusing so "Open containing folder" is better.

I think changing the default action is not really needed if you have directly both options and we can add a tooltip to the folder icon to show "open containing folder" on hover and at the link hover something like "open link".

**Comment by feinstaub** [comment]
Yes, good idea.

**Comment by AWolf81** [comment]
The icon click to open the containing folder is working in my working copy. I'll push this soon to branch [improve-issue-32](https://github.com/feinstaub/firefox_addon_local_filesystem_links/tree/improve-issue-32).

I have a question to the tooltip. Do you think it's OK to only show the tooltip for the icon that's opening the containing folder? At the moment, it looks like this:
![screenshot](http://i.imgur.com/8Ymi7tU.png)

We can add a tooltip later to the link as well but for now I think that's enough. I'll also add a preference to disable / enable the tooltip. (By default enabled)

I have to do some style checks now and add the pref. but direct link and icon click is working.

**Comment by MurzNN** [comment]
I think that icon is enough, this tooltip is too large. Maybe add standard "title" attribute to it and thats all. But I prefer to use menu item instead of icon, because use opening file folder not so often, and don't want to see icons on every link, so for me I disable icon in extension settings.

**Comment by AWolf81** [comment]
OK, thanks for your feedback and you right. Tooltip is a bit large. I'll try to make it smaller with the font size.
