### ISSUE TITLE
Not work in dokuwiki with tabinclude plugin

### ISSUE THREAD

**Issue by Mannshoch** [feinstaub/firefox_addon_local_filesystem_links#33]
Even the rescan button not work.

Description of the Plugin: https://www.dokuwiki.org/plugin:tabinclude
Demo of the Plugin: http://symplus.edu-wiki.org/doku.php?id=tabinclude_plugin

**Comment by feinstaub** [comment]
thanks for reporting

**Comment by feinstaub** [comment]
see also https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/24

**Comment by feinstaub** [comment]
I will close old bugs. Is this still an issue? If yes please don't hesitate to reopen it.

**Comment by Mannshoch** [comment]
Thanks for this update. It works.
