### ISSUE TITLE
Remove deprecated sdk/widget

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#35]
Comment from last review (0.99.37):

> Please note the following for the next update:
> 1) The 'widget' module has been deprecated due to a number of performance and usability > issues, and is slated to be removed from the SDK in the near future. Please use the 'sdk/ui/button/action' or 'sdk/ui/button/toggle' module instead.
> https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action
> https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle

**Comment by sweoggy** [comment]
This might be the reason to why the addon isn't working, at all, in Firefox 40.0a2/41.0a2

**Comment by feinstaub** [comment]
@sweoggy: you are right https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/widget "Deprecated in Firefox 29 and removed in Firefox 38.". So fixing this is first priority.

**Comment by feinstaub** [comment]
bdef48140cc2a5106a4f9302fe9fdd733a8c743c
