### ISSUE TITLE
Optionally disable parts of  "Local Filesystem Links" extension functional (hide icons).

### ISSUE THREAD

**Issue by MurzNN** [feinstaub/firefox_addon_local_filesystem_links#36]
Most of local links opens normally via custom settings:
```
user_pref("capability.policy.policynames", "localfilelinks");
user_pref("capability.policy.localfilelinks.sites", "http://mylocalsite.com http://anothersite.ru");
user_pref("capability.policy.localfilelinks.checkloaduri.enabled", "allAccess");
````
After this all local links open via one click normally without any extension, and additional icons is useless.

So I need "Local Filesystem Links" extension only for "Open containing folder" functionality, and this will be good to see only in right click menu.

Will be good to have option for disable functional of your extension: for me - disable scan page and adding icons, and only act on right click, add "Open containing folder" menuitem.

**Comment by feinstaub** [comment]
The following changes would be needed:

Addon Preferences:
- add option "Globally disable hyperlinks scanning"
- add option "Do not show folder icon"

Context menu:
- add item "Open containing folder"

**Comment by AWolf81** [comment]
Hiding of icon is added in PR #50. Merged to master today. So it's not in Mozilla gallery yet.

A global disable of the link is not implemented. If you're clicking the link text it will open it with the addon. Right click context menu to reveal folder is also added.

**Comment by feinstaub** [comment]
The addon is now in the AMO review queue.

**Comment by MurzNN** [comment]
Thanks! Updated version already available. Option "Enable link icons" works well, but context menu item "Open containing folder" seems missing.

**Comment by feinstaub** [comment]
The menu item is named "Link addon - reveal..."
