### ISSUE TITLE
v0.99.37 no longer works with Firefox 39 or later

### ISSUE THREAD

**Issue by 4leite** [feinstaub/firefox_addon_local_filesystem_links#37]
Hi, 
The latest update for firefox seems to have broken this on every system (windows 7/8) I have tested on.

Happy to supply more info / testing as required.

Cheers

**Comment by sweoggy** [comment]
I can comfirm this, I believe it's caused by https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/35. In the meantime you might want to consider using latest Firefox ESR https://www.mozilla.org/en-US/firefox/organizations/all/

**Comment by feinstaub** [comment]
@4leite: As a quick fix please go down the addon's page and expand the "Version information" section. There, click "See complete version history". Hover over "Version 0.99.25.1-signed" and click "Add to Firefox". This will install the previous version.

**Comment by 4leite** [comment]
@sweoggy Installing Firefox ESR worked around teh problem for me, presumably because it doesn't contain the update you referenced.

@feinstaub your solution did not work for me, as above seems to be introduced by an update to firefox, as opposed to the latest version of this plugin.

**Comment by ThomasKaufmann** [comment]
Can confirm this. After the update to Firefox 39 the extension disappeared from the list of installed extension. Reinstalling did not help either. Switching back to Firefox 38 or to ESR release (also 38) worked.

**Comment by feinstaub** [comment]
After bdef48140cc2a5106a4f9302fe9fdd733a8c743c, unit tests do run again (use nigthly build 42.0a1):
cfx test -p _pt -b ~/dev/share/firefox-42.0a1/firefox 
...
23 of 26 tests passed.

Strangely, the addon does not work at all when doing this:
cfx run -p _pr -b ~/dev/share/firefox-42.0a1/firefox

**Comment by feinstaub** [comment]
The addon seems not to loaded at all, even when start the nightly directly and add the created xpi file manually. Currently no idea how to debug this. Maybe there is something wrong with my setup.

**Comment by feinstaub** [comment]
Can someone confirm that current master is working with any FF version after 38? Then I'll publish a new xpi.

**Comment by ThomasKaufmann** [comment]
I had no luck with firefox 39.
I run cfx run from the downloaded master directory. It says 0.99.38 is installed but still no folder icons next to the links.

**Comment by ThomasKaufmann** [comment]
same procedure works with the 38 esr release.

**Comment by feinstaub** [comment]
Thanks for trying. I wonder how to debug this problem...

**Comment by feinstaub** [comment]
I'm going through https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Troubleshooting

cfx testall # with FF 38

yields
```
Testing cfx...
..................Warning: missing module: sdk/panel
Warning: missing module: sdk/tabs.js
Warning: missing module: sdk/panel
Warning: missing module: sdk/tabs.js
..........
(process:4137): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
```
and then it hangs. So compared to the expected result on the troubleshooting site there seems to be something wrong.

With the nightly build there is more output
cfx testall -b ~/dev/share/firefox-42.0a1/firefox

output: http://paste.opensuse.org/30433716
But the process does not finish (Firefox windows still open).

**Comment by sweoggy** [comment]
I will probably take a look at this tomorrow if you haven't figured it out by then :) Will fix my pull request first though.

**Comment by feinstaub** [comment]
On the #jetpack IRC channel was suggested to use jpm instead of cfx.

I did
jpm -b ~/dev/share/firefox-42.0a1/firefox test -p ./_pt
and got:
```
JPM undefined Error: ENOENT, stat '/home/dev/src/firefox_addon_local_filesystem_links/_p1/chrome_debugger_profile/lock'
```

see also https://github.com/mozilla/jpm/issues/287

**Comment by sweoggy** [comment]
I am able to run JPM with latest 41.0a2. However the tests never finish (not sure if it's supposed to). I get a few errors while it runs:

console.log: alien-local-filesystem-links: [JavaScript Error: "A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise


And a few errors related to launch-local-process.js:

Full Message: Module `./test/launch-local-process` is not found at resource://ji
d1-jazc7z53jemo5q-at-jetpack/test/launch-local-process.js
Full Stack: @resource://jid1-jazc7z53jemo5q-at-jetpack/test/test-launch-local-pr
ocess.js:11:22
findTests/</getNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test
-finder.js:164:25
findTests/</<.getNext@resource://gre/modules/commonjs/sdk/deprecated/unit-test-f
inder.js:197:32
runNextTest@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:518:14
startMany@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:532:12
findAndRunTests/<@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:28
:1
Handler.prototype.process@resource://gre/modules/Promise-backend.js:920:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:799:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.j
s:738:39
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise-bac
kend.js:738:7
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise-backend.js:762
:7
Promise.prototype.then@resource://gre/modules/Promise-backend.js:445:5
this.XPIDatabase.getAddon@resource://gre/modules/addons/XPIProviderUtils.js:1077
:12
XPIDB_getVisibleAddonForID@resource://gre/modules/addons/XPIProviderUtils.js:111
4:1
XPI_getAddonByID@resource://gre/modules/addons/XPIProvider.jsm:4021:5
callProviderAsync@resource://gre/modules/AddonManager.jsm:248:12
promiseCallProvider/<@resource://gre/modules/AddonManager.jsm:273:53
Promise@resource://gre/modules/Promise-backend.js:379:5
promiseCallProvider@resource://gre/modules/AddonManager.jsm:272:1
AMI_getAddonByID@resource://gre/modules/AddonManager.jsm:2149:47
AM_getAddonByID@resource://gre/modules/AddonManager.jsm:2880:5
getAddon@resource://gre/modules/commonjs/sdk/addon/installer.js:118:3
getSuites@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:57:
10
findTests@resource://gre/modules/commonjs/sdk/deprecated/unit-test-finder.js:145
:12
findAndRunTests@resource://gre/modules/commonjs/sdk/deprecated/unit-test.js:27:3

**Comment by sweoggy** [comment]
I fixed the tests in 444efdf31e46bff012e5819cc30d301a47bcfed1, unfortunately all tests passes...

**Comment by feinstaub** [comment]
> I fixed the tests in 444efdf, unfortunately all tests passes...

Hmm, all tests pass? How that's unfortunate...?

About the error messages: did you check https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Unit_testing or https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx_to_jpm#Requiring_modules_from_test_code?

Apart from the unit tests, did you try if the addon itself works with 41.0a2?

**Comment by sweoggy** [comment]
@feinstaub it's unfortunate because the addon itself doesn't work. It seems like it isn't initialised properly, hyperlink-scanner.js is for example never visible in debugger -> sources. I tried it with 41.0a2, yes. The error messages went away with the 444efdf commit.

**Comment by feinstaub** [comment]
> It seems like it isn't initialised [...] never visible in debugger

I have the same impression. Somehow I got it to be seen in the debugger (I think I use the Debug button which is available when firefox is started via cfx/jpm run) but the breakpoints did not hit.

So, I conclude: we don't know what's wrong and how to debug it.

The next step would be be contact the mozilla sdk guys in the #jetpack IRC channel or write to the mailing list.

**Comment by MrWillow** [comment]
Can anybody fix this problem? Please?
I am not knowledgeable enough to help out, but I would love to keep this plug-in. We use it a lot internally to jump to the right directory in a *huge* file system.

**Comment by sweoggy** [comment]
I plan to take a look at this again later this week if noone else has fixed it by then.

**Comment by sweoggy** [comment]
I had a chat with freaktechnik at #jetpack today. He came to the following conclusion: 

"so changing the hyperlinkScanner.include to settings.scannerIncludePatternArray in the constructor at least fixes the initial patterns, sweoggy"

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1189781

**Comment by feinstaub** [comment]
fixed in v0.99.38

**Comment by feinstaub** [comment]
On 2015-08-01 I tried to submit v0.99.38 (which works for FF39+) to the Mozilla addon gallery but it was rejected two times. After the second time I wrote this email to amo-editors@mozilla.org but got no answer yet.

```
Hallo,

thanks for the review. I created the xpi file using `jpm xpi` (see
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_xpi) and a .jpmignore with

.*
*.xpi
start_sdk.cmd
start_sdk.sh
.*/
doc/
evalpage/
intellij_module/
reviews/
test/webserver/

I wonder how else the xpi file should be created.

Thanks

On 01/08/15 20:20, amo-editors@mozilla.org wrote:
>
> Your add-on, Local Filesystem Links 0.99.39, has been reviewed by an editor and did not meet the criteria for being hosted in our gallery.
>
>
> Reviewer:
> erosman
>
> Comments:
> Your version was rejected because of the following problems:
>
> 1) Add-on contains duplicate/hidden/unused/unnecessary files or folders. These complicate the review process and may contain sensitive information about the system you created the XPI on. Please correct your packaging process so that these files aren't included.
>
>  jid1-JAzC7z53jemo5Q@jetpack-0.99.39/ and its content are a copy of the addon content
>
>
> Please fix them and submit again. Thank you.

```

**Comment by rixtech** [comment]
Version 0.99.39b works sweetly for me in Firefox 39.0.3
Thanks

**Comment by dadopa25** [comment]
@rixtech:  where can I download the version 39.0.3? Thanks

**Comment by sweoggy** [comment]
@dadopa25 use the latest version here https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/versions/

**Comment by Tenkryss** [comment]
@sweoggy the 39b does not appear on that link...

**Comment by feinstaub** [comment]
Two days ago the 39b got rejected. This is the reason why it is not available anymore. Here is the review result:

```
On 10/09/15 10:18, amo-editors@mozilla.org wrote:
> 
> Your add-on, Local Filesystem Links 0.99.39b, has been reviewed by an editor and did not 
meet the criteria for being hosted in our gallery.
> 
> 
> Reviewer:
> erosman
> 
> Comments:
> Your version was rejected because of the following problems:
> 
> 1) Your add-on includes a JavaScript library file that doesn't match our checksums for known
 release versions. We require all add-ons to use unmodified release versions, obtained 
directly from the developer's website.
> 
> We accept JQuery/JQuery-UI libraries downloaded from 'ajax.googleapis.com', 'jquery.com' or
  'jqueryui.com'; and used without any modification. Minified versions are fine. (file-name change 
does not matter)
> I'm sorry, but we cannot accept modified, re-configured or customized libraries.
> 
> data/js/jquery-ui-1.8.16.custom.min.js
> 
> Please fix them and submit again. Thank you.
> 
> 
> 
> This version of your add-on has been disabled. You may re-request review by addressing the 
editor's comments and uploading a new version. To learn more about the review process, please 
visit https://addons.mozilla.org/developers/docs/policies/reviews
> 
> If you have any questions or comments on this review, please reply to this email or join 
#amo-editors on irc.mozilla.org
> --
> Mozilla Add-ons
> https://addons.mozilla.org
```

**Comment by feinstaub** [comment]
The JQueryUI is currently used to generate a custom settings page. In order to re-establish compatibility I suggest to remove the settings page without replacement. The only option is to globally enable or disable hyperlink scanning. This could later be replaced by per page settings. RR welcome.

**Comment by cdickens77** [comment]
Are there any status updates on getting this add-on updated to work with the latest versions of Firefox?  I see the steps to access Version Information and download v0.99.39b directly, but on the version history page (https://addons.mozilla.org/en-US/firefox/addon/local-filesystem-links/versions/), I do not see the link to download this version - only 37 seems to be available.  Could someone put the XPI file on a file hosting service and link directly?  Thanks!

**Comment by feinstaub** [comment]
Patches are welcome to fix the problem at the source.

**Comment by AWolf81** [comment]
I also have the problem and the plugin version from mozilla add-ons with FF 42.0 (Win 8.1) is not working. No link button is visible. I've cloned master and tested it locally and it is working. All tests are passing 31 of 31 with `jpm test`.

I have some questions to your source code:
- Is the [`require('./translate-demo');`](https://github.com/feinstaub/firefox_addon_local_filesystem_links/blob/master/lib/main.js#L19) needed? I can't see it in action in the browser. Why is it there?
- Where is jQueryUI used? I can't get the menu in the browser. Is it accessible with a right click at the link? Have you removed it? How can I get that menu back? I think Mozilla only complaint the custom jqueryUI library that you're using and if you'd use the stable version from the mentioned source it should be OK.

I'd propose to remove all unnecessary parts from source to get a working version back to Mozilla add-on gallery. I could send you a PR once I have a better understanding of your code.

I'd like to help to fix these problems because I think your add-on is really useful. I'd like to use local links at [trello](https://trello.com/) so I can share links with my collegues that are having the same network access.

**Comment by feinstaub** [comment]
> Is the require('./translate-demo'); needed? I can't see it in action in the browser. Why is it there?

It is not required. It is there for historical reasons (it was a demo to use a remote webservice to translate text) and can be removed.

**Comment by feinstaub** [comment]
> Where is jQueryUI used?
It is used on this options page: data/main-wid/options-panel.xhtml

In toolbar-panel.js/xhtml there is a button #button_options. When it is clicked, "show_options" is emitted which opens the options-panel which was introduced to have options _per page_ instead of only global ones.

But: since bdef48140cc2a5106a4f9302fe9fdd733a8c743c the options panel is no longer accessible because the sdk/widget API was dropped. It created an icon for Local Filesystem Links in the status bar / add-on panel which could be clicked.

**Comment by feinstaub** [comment]
> I'd propose to remove all unnecessary parts from source to get a working version back to Mozilla add-on gallery. I could send you a PR once I have a better understanding of your code.

Please do so. I appreciate your help.

**Comment by feinstaub** [comment]
The new version 0.99.41a is currently in the Mozilla review process

**Comment by MrWillow** [comment]
Thank you aWolf81 and feinstaub for your efforts! I just want to let you know people appreciate it. :+1:

**Comment by dsbcpas** [comment]
Hooray!

**Comment by feinstaub** [comment]
I close this issue now, though the latest review was not successful yet. There is a security vulnerability that needs fixing, I opened a separate issue for it: https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/46
