### ISSUE TITLE
[tech] move lib/main.js to index.js

### ISSUE THREAD

**Issue by feinstaub** [feinstaub/firefox_addon_local_filesystem_links#41]
move lib/main.js to index.js to adhere the new addon standard

**Comment by AWolf81** [comment]
@feinstaub is it only remaining to `index.js` or also move it to root folder? I would only rename it and keep it in the lib folder.

**Comment by feinstaub** [comment]
I think it is also moving to root folder. (But I am not sure, I read it in some tutorial for new addons. Sorry that I did not include a reference.)

**Comment by feinstaub** [comment]
"Now you can write the add-on's code. Unless you've changed the value of "entry point" ("main" in package.json), this goes in "index.js" file in the root of your add-on." (https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29)

When this is done I could make a release.

**Comment by feinstaub** [comment]
@AWolf81
