### ISSUE TITLE
Any plans of Thunderbird support?

### ISSUE THREAD

**Issue by NemoKOF** [feinstaub/firefox_addon_local_filesystem_links#55]
Dear Author,
Your add-on works very well! It gets updated, has many users. 
I have a question - do you plan to support Mozilla's email client - Thunderbird? It is very good and popular and such an addon would be a blessing in many corporate environments - many people are sending paths to files and Thunderbird works exactly like FF - those links are not working, they get replaced with file:/// stuff.

Is there any possibility that you would support Thunderbird in the future?

Best regards,
Przemek

**Comment by feinstaub** [comment]
Hello, thanks for the interest. Currently, there is no plan to have this on Thunderbird. I didn't look if there already are existing / similar solutions available. I also think it desirable to have this feature there.

**Comment by feinstaub** [comment]
Is this still an issue? Then please re-open.

**Comment by NemoKOF** [comment]
Yes, it's still an issue.
