### ISSUE TITLE
Multiple icons in trello card

### ISSUE THREAD

**Issue by AWolf81** [feinstaub/firefox_addon_local_filesystem_links#56]
In Trello there are three icons at every link like in the following screenshot:
![screenshot](http://img.ctrlv.in/img/16/03/04/56d8d84ae90b1.png)

I couldn't re-create the issue in a fiddle / test case at the moment.
It seems like the mutationObserver gets triggered multiple times. It's not easy to investigate because I don't know how the card is loaded (sure with ajax but there must be more that's disturbing...).

In my test a normal ajax request is no problem that's adding the requested data directly into the DOM. Maybe I have to check if it's related to the popup.

Any ideas what could be the problem?

Affected version 0.99.42 (latest from moz. gallery) tested with FF 44.0.2 (Win 8.1 64bit).

**Comment by feinstaub** [comment]
Interesting problem. What about checking if a specific <a href...> element already is instrumented with the alien local link icon and context menu and then prevent an additional addition?

**Comment by AWolf81** [comment]
Fixed with PR #58.
(I've added a check in the observer so that icons are only added if there is not already an icon.)
