### ISSUE TITLE
Links with backslashes not detected

### ISSUE THREAD

**Issue by AWolf81** [feinstaub/firefox_addon_local_filesystem_links#57]
In [perinorm.com](https://www.perinorm.com) a website for managing standards (DIN / ISO etc) they're creating links to local files like
`<a href="file:\\\\\server\folder\document.pdf">standard.pdf</a>`

And that's not detected by local link addon at the moment because it only detects `file://` (slashes). Links are not clickable and no icon at the link. (I know the URI syntax is not correct at perinorm but it would be great to support backslashes too.)

The links can only be  opened by copying to a new tab.

I think I've already read a similar issue here but I couldn't find it.

So I think we have two options:
- add a user preference that enables backslash replacement on a per website basis (pretty complicated)
- add the selector `file:\\` and check if the addon is opening the link correctly. (that's easier but I'm not sure if it's working.)

**Comment by feinstaub** [comment]
In any case, please add a user option with

title: "Enable non-standard link handling 1"
description: "Normally, local file URLs start with file://. Enable this option to also detect the non-standard file:\\ notation (with backslashes)."

which is disabled by default. Public sites should adhere to the basic web standards.

**Comment by AWolf81** [comment]
Fixed with PR #58.
