### ISSUE TITLE
Greater leading appears due to LFL

### ISSUE THREAD

**Issue by Peter0** [feinstaub/firefox_addon_local_filesystem_links#63]
When Local Filesystem Links is active, it makes lines containing a local filesystem link appear with more distance to other lines. Refer attached image: On top, there is a cutout of a document as displayed with LFL active and below the same document when displayed with LFL disabled. (Just became aware of fact that I took a unfavourable cutout range. All three lines got a local link, each.)

Local Filesystem Links 0.99.42
FF 44.0.2
Win-7

**Comment by Peter0** [comment]
"
![Uploading LFL_leading.png…]()
Something went really wrong, and we can’t process that file."

**Comment by AWolf81** [comment]
I can't see this issue in my tests. 

Can you please add your html markup and css so I can check why this is happening? Or even better could you create a [jsfiddle](https://jsfiddle.net/) that's showing the issue?

**Comment by Peter0** [comment]
I hope It will be fine!
Many Thanks – Peter
