### ISSUE TITLE
Both the actual link as well as the little folder symbol do the same

### ISSUE THREAD

**Issue by Peter0** [feinstaub/firefox_addon_local_filesystem_links#64]
Both the actual link as well as the little folder symbol do the same – open the link-target.

In some ancient days, only the actual link opened the link-target, as opposed to the little folder, which opened an Explorer window of the very directory containing the link-target with marked link-target (as if single-clicked on it).

Please change behaviour back to ancient days.

Thanks a lot nevertheless.
Local Filesystem Links 0.99.42
FF 44.0.2
Win-7

**Comment by AWolf81** [comment]
Yes, that's the current behaviour of v0.99.42. 
There was a larger change to the addon to make it compatbile with latest FF and some points aren't perfect yet.

We changed the behaviour back in the latest master (see comments [here](https://github.com/feinstaub/firefox_addon_local_filesystem_links/issues/32)) and it will be added in the next released version. 

So click on link text will open the file and icon click will open the containing folder in Windows explorer. But the file won't be marked in the explorer. I'll check if that's possible.

**Comment by Peter0** [comment]
Sorry, wasn't quite sure yesterday if I already posted this issue – apparently I did.
Is it possible to mark this issue as 'done'/'cleared', but leave it open until next release to prevent other users from opening the same issue in their own words?

**Comment by AWolf81** [comment]
No problem. 
We'll keep this open until the new version is available.

**Comment by AWolf81** [comment]
Fixed with 0.99.46 - version now available in Mozilla gallery.
