### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by MacgyverJohnson** [feinstaub/firefox_addon_local_filesystem_links#67]
Hi there dev..
going to file:///C:/Users/ or any other location, when the folder is right clicked and reveal link/execute link is clciked eveything is woking fine....but highlighting any file url and rightclicking to select execute link doessnt work....shows an error....also no file icons are shown :(
here are console logs
"Handler function NM_observeActivity threw an exception: TypeError: aChannel.loadInfo is null
Stack: NetworkMonitor.prototype._createNetworkEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:873:1
NM__onRequestHeader@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:937:5
NM_observeActivity@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:710:7
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
Line: 873, column: 1" ThreadSafeDevToolsUtils.js:80
"Handler function NM_observeActivity threw an exception: TypeError: aChannel.loadInfo is null
Stack: NetworkMonitor.prototype._createNetworkEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:873:1
NM__onRequestHeader@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:937:5
NM_observeActivity@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:710:7
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
waitForSyncCallback@resource://services-common/async.js:102:7
querySpinningly@resource://services-common/async.js:212:12
HistStore__findURLByGUID@resource://gre/modules/services-sync/engines/history.js:185:12
createRecord@resource://gre/modules/services-sync/engines/history.js:354:15
SyncEngine.prototype._createRecord@resource://services-sync/engines.js:856:18
SyncEngine.prototype._uploadOutgoing@resource://services-sync/engines.js:1468:17
SyncEngine.prototype._sync@resource://services-sync/engines.js:1533:7
WrappedNotify@resource://services-sync/util.js:146:21
Engine.prototype.sync@resource://services-sync/engines.js:666:5
_syncEngine@resource://services-sync/stages/enginesync.js:213:7
sync@resource://services-sync/stages/enginesync.js:163:15
onNotify@resource://gre/modules/services-sync/service.js:1279:7
WrappedNotify@resource://services-sync/util.js:146:21
WrappedLock@resource://services-sync/util.js:101:16
_lockedSync@resource://gre/modules/services-sync/service.js:1269:12
sync/<@resource://gre/modules/services-sync/service.js:1261:14
WrappedCatch@resource://services-sync/util.js:75:16
sync@resource://gre/modules/services-sync/service.js:1249:5
Line: 873, column: 1" ThreadSafeDevToolsUtils.js:80
"Handler function NM_observeActivity threw an exception: TypeError: aChannel.loadInfo is null
Stack: NetworkMonitor.prototype._createNetworkEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:873:1
NM__onRequestHeader@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:937:5
NM_observeActivity@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:710:7
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
Line: 873, column: 1" ThreadSafeDevToolsUtils.js:80
[Exception... "Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIWebNavigation.loadURIWithOptions]"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: chrome://tabmixplus/content/changecode.js line 179 > eval :: _loadURIWithFlags :: line 29"  data: no] changecode.js line 179 > eval:50:0
[Exception... "Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIWebNavigation.loadURIWithOptions]"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: chrome://tabmixplus/content/changecode.js line 179 > eval :: _loadURIWithFlags :: line 52"  data: no] changecode.js line 179 > eval:184:0
"Handler function NM_observeActivity threw an exception: TypeError: aChannel.loadInfo is null
Stack: NetworkMonitor.prototype._createNetworkEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:873:1
NM__onRequestHeader@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:937:5
NM_observeActivity@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:710:7
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
Line: 873, column: 1" ThreadSafeDevToolsUtils.js:80

![mell](https://cloud.githubusercontent.com/assets/17729946/15104295/442a120e-15d8-11e6-9d64-4a612dacf514.gif)

total noob here so I dont if thats working fine or giving error
@feinstaub @AWolf81 @sweoggy @EnriqueSoria

**Comment by AWolf81** [comment]
Thanks for your detailed issue description. 

Where do you get that stack trace? I couldn't see it in my console.

I think that issue should be improved. (If I have some time to fix it.) I couldn't find a good fix yet.
During my test it only worked if I've selected with `file:///` and it could open the folder.

Seems like the addon is not correctly replacing the forward slashes with backslashes for Windows if no file protocol is in the selected link. In the latest master `open containing` folder is working with selecting `c:/users` because it adds the file:/// to the path. But link open is also not working.

The icons are not showing because the links in directory browser are special links with-out `href="file://c:/"` in the a-tag. Not sure how to detect these, maybe we could check the url of the tab and if it starts with `file://` we're enabling special icon handling for anchor tags with class `file`. 

Also the href of that links is with-out absolute path because it uses `base` tag in the header. Not sure if that's a problem for the open containing folder icon. So there are some points to check to make the icons work.

**Comment by feinstaub** [comment]
Is this still an issue? Then please re-open.
