### ISSUE TITLE
Local Filesystem Links 0.99.42.xpi Inactive

### ISSUE THREAD

**Issue by forzagenki** [feinstaub/firefox_addon_local_filesystem_links#69]
Hello,

I created Local Filesystem Links 0.99.42.xpi successfully.
And I installed it to Firefox with changed the value of the "xpinstall.signatures.required." to "false".
But the icon appeared on the tool bar is grayout and showing the message "Local link addon (current tab: inactive)".
I don't know how to change it to active.

I am using Firefox ESR 45.2.0 under Windows 7.

**Comment by AWolf81** [comment]
Hello,

have you checked your whitelist settings? 
If there is a * or empty it should enable every page. But I think new blank tabs are shown as inactive by default because no url to check available.

**Comment by forzagenki** [comment]
I apologize for any comfusion.
I can link to local files, but I can not open (explore) local files.
The problem is that it does not show a link icon close to the link.

Thank you,

**Comment by forzagenki** [comment]
Again,

I used Local Filesystem Links 0.99.38 on Firefox ESR 38.8.0.
My main purpose of using Local Filesystem Links is to open folders like Windows Explorer.
It's very convenient.

But Firefox was updated to ESR 45.2.0 and I could not use Local Filesystem Links 0.99.38.
So I installed Local Filesystem Links 0.99.42 by using a xpi file created.
I could use ordinary file links functions, but folder icon does not appear on the right side of the link.
And the icon appeared on the tool bar is grayout and showing the message "Local link addon (current tab: inactive)". I don't know how to change it to active.

Is this in the specifications of Local Filesystem Links 0.99.42 when using Firefox ESR 45.2.0?

**Comment by AWolf81** [comment]
Are you using the directory browser of FF? Then issue #67 is related.

The file browser creates links differently and that's why the icons are not added to the links.

Probably the inactive/active handling is not correctly working with directory browser. I need to check how to fix. (The icon changes automatically to active on any whitelisted url.)

**Comment by forzagenki** [comment]
Leave a commentThank you AWolf81,

I could find a "Link addon" menu and "Open link" or "Open containing folder" appropriately.

(html discription)
<a href="file://C:/windows">C:/windows</a><br>

(Firefox browser)
C:/Windows

right click 
    shows "Link addon"
        sellect "Open link" ---> pic1
        sellect "Open containing folder" ---> pic2

An inconvenience for me is only that the file icons are not added to the links.
C:/Windows (no file icons!!!)

![pic1](https://cloud.githubusercontent.com/assets/19944989/16411924/924faf1c-3d64-11e6-9a6b-2c90c50198e4.jpg)
![pic2](https://cloud.githubusercontent.com/assets/19944989/16411948/a693bca2-3d64-11e6-9d8c-1109b6121231.jpg)

**Comment by forzagenki** [comment]
Sorry,

(html discription)
<a href="file://C:/windows">C:/windows</a><br>

(Firefox browser)
C:/windows

**Comment by forzagenki** [comment]
Sorry again,

(html discription)
href="file://C:/windows" in the a-tag

**Comment by AWolf81** [comment]
I'm closing this to reduce the open issues. 
If you're still having the problem please let me know. (I don't understand your problem - I would need more details.)

**Comment by forzagenki** [comment]
Please close it.

I will use Version: 0.99.37 until the problem is solved.

 

Thank you,
