### ISSUE TITLE
Links with "spaces" aren't opened

### ISSUE THREAD

**Issue by snyfer** [feinstaub/firefox_addon_local_filesystem_links#78]
For example the following link is only underlined as a link only till the first space in it "file:///\AZMSHARE_1_in arbeit"

Is there any way of some kind of functional character to get the whole link recognized as link?

BR

**Comment by AWolf81** [comment]
The link should contain four forward slashes (two for file:// and two for the UNC network address //diskstation) e.g.
`<a href="file:////diskstation/home/in arbeit/test.txt">in Arbeit</a>`

It should be no problem if the network share contains a space character expect the host name. Host name shouldn't contain spaces. That can cause troubles at some systems (see these forum [posts](http://lime-technology.com/forum/index.php?topic=17450.0)).

This will only work for Windows. Linux would need `smb://` protocol and that currently not handled by the addon.

**Comment by AWolf81** [comment]
I'm closing this because spaces should be no problem. 
If there are still problems please let me know.
