### ISSUE TITLE
No icons shown in firefox 45.3.0

### ISSUE THREAD

**Issue by O-Meyer** [feinstaub/firefox_addon_local_filesystem_links#80]
I just noticed, that the addon (v 0.99.42) does no display any icons anymore. 

I have requested to show icons in the settings.
The entry in the context menu, does what I expect it to do.

I noticed from other issues, that this might be a font problem with my installation. Please let me know, what I can do to solve the issue for me and/or to help you fix the problem for everyone.

**Comment by AWolf81** [comment]
Sorry, for late response.

The font issue was at an older version of Firefox (I think FF 38). I've tested 0.99.42 with Firefox portable ESR 45.3.0 and the icons are visible at my machine. I couldn't find a portable non ESR version of Firefox 45.3.

Do you still have the problem?
How is the url of the link that's not working?

**Comment by O-Meyer** [comment]
No need to be sorry. Thank you for replying.

I do still have the problem.

As you can see in the screenshot I am following the local link `file:///c:/tmp/NoIcon`
Firefox will then display the folder content (in this case another folder and file). I like to click on an icon besides "Subfolder" that opens that folder in Windows explorer.  That icon does not appear and I have to select "Link addon - reveal selected link" in the context menu.

![scrshot-index von file____c__tmp_noicon - mozilla firefox-20161004090424](https://cloud.githubusercontent.com/assets/16287388/19065061/97381fd8-8a11-11e6-8c7a-07b8d418c032.png)

I saved the page. Maybe the HTML code that my firefox generates when browsing a local folder is different to what is expected: 
[Index von file _C _tmp_NoIcon.zip](https://github.com/feinstaub/firefox_addon_local_filesystem_links/files/507833/Index.von.file._C._tmp_NoIcon.zip)


What additional information might help you help me?

**Comment by AWolf81** [comment]
Thanks for your details. That's enough to check if an improvement is possible.

I know this issue but I don't have a fix yet. Firefox is creating the links differently and the addon is not detecting them. See issue #67.

I need to check if I can fix this for firefox file browser. 
I have an idea how I can fix this: FF is using base tag and that's creating the link like the addon is expecting it but it's not visible to the plugin at the moment. Maybe I can add a script that checks if the url is containing file protocol and then it handles links differently.

But checking will take some time. I'll send you info here as soon I've created something.

**Comment by O-Meyer** [comment]
Thanks. Should I follow the other issue and we close this as duplicate (or some similar concept that matches this issue tracking system)?

**Comment by feinstaub** [comment]
Is this still an issue? Then please re-open.
