### ISSUE TITLE
alien-local-filesystem-links: Couldn't open file...

### ISSUE THREAD

**Issue by maciejnb** [feinstaub/firefox_addon_local_filesystem_links#83]
I have a problem with direct opening the file below with single click on URL:

![obraz](https://cloud.githubusercontent.com/assets/26298856/23744732/b18e769c-04b5-11e7-92f6-801e733d16ef.png)

URL: file://///XXXXXXXX/Centrala-Wspolne/XXX/41_Ryzyko Operacyjne/Rejestr incydentów_zdarzeń operacyjnych/Rejestr_Incydentów i Ryzyk_IT_aktualny.xlsm

but opening in that way works OK: right mouse button click on URL -> Link addon -> Open link

**Comment by AWolf81** [comment]
Thanks for mentioning this issue.

This is probably the same issue as #84. I'm working on it.

**Comment by AWolf81** [comment]
Please have a look at issue #84 for the latest info. 
I'm closing this issue because it's the same problem.
