### ISSUE TITLE
Cant open File System Link

### ISSUE THREAD

**Issue by PatrickEiser** [feinstaub/firefox_addon_local_filesystem_links#89]
Hello,
after Mozilla closed now complete the options to use file system links without an extension, I was persuade my boss that we use an extension. But now I have the problem that its no more funktion.... in an earlyer version it was funktion but now not anymore...
I got an littel box at the right corner where stand 
"alien-local-filesystem-links
Konnte Datei nicht öffnen file:///........."
Is there anywhere an log or something like that where I can look where is the Problem?

**Comment by AWolf81** [comment]
What Firefox version do you use? 
Can you please post an example of a link that is not working? 

Because it's important to have the link correctly.

You could check if there are any error messages in addon debug console accessed with the following url: about:debugging#addons

**Comment by PatrickEiser** [comment]
I tryed it with 53.0.2 (32-Bit) and 50.1.0 .
Link is: "file:///dfsroot/Organisation/01 Managementsystem/05 Vorlagen & Hilfsmittel"
And sorry but I dont know where i have to find there errors.....

Regards Patrick

**Comment by AWolf81** [comment]
dfsroot is a network drive, right?

Please try to add two more slashes after file:/// so the link should work if you write it like this:
file://///dfsroot/Organisation/01 Managementsystem/05 Vorlagen & Hilfsmittel"

So 5 slashes are recommended and should work. But I think it will also work with 4 slashes file:////dfsroot...

**Comment by PatrickEiser** [comment]
Hello,
yes dfsroot is an Network drive :)

with 3 slashes it look so:
![grafik](https://cloud.githubusercontent.com/assets/28706561/26140974/dc39f358-3ad9-11e7-86df-49ee78239dae.png)
and with 4 or 5 it looks so:
![grafik](https://cloud.githubusercontent.com/assets/28706561/26141032/1ef66e88-3ada-11e7-8188-a15dba866c01.png)
and i noticed that the plugin is hang up when i first try to open the links with 4 or 5 slashes. Then i have to deaktivate the plugin and have to aktivate again and than i have to klick first an link with 3 slashes bevor i can klick an link with more.

**Comment by PatrickEiser** [comment]
@AWolf81 or @feinstaub Are you 2 alive?

**Comment by AWolf81** [comment]
Hallo Patrick,

ich hab deinen Kommentar ganz übersehen, sorry.

In welcher FF Version tritt das Problem auf?
Ist das Problem auch bei lokalen Dateien vorhanden?

Ich werde mir das heute Abend anschauen und versuchen, ob ich das Fehlverhalten auch hinbekomme.

Ich weiß, dass Mozilla bald die Addons deaktivieren möchte. Aber der Umstieg auf WebExtensions ist nicht ganz einfach, da man dann auch eine separate Windows/Linux App für den Dateizugriff benötigt.

Ich komme aber leider zeitlich gerade nicht dazu.

Gruß Alexander

**Comment by PatrickEiser** [comment]
Hallo Alexander,
wir laufen aktuell unter der Version 53.0.2 (32-Bit)
So Problem gefunden..... Wir arbeiten wenn wir pfadangaben machen mit dfsroot. Und euer Plugin arbeitet mit local eingebundenen laufwerke also wenn ich das netzlaufwerk mit S einbinde muss in der Pfadangabe zur datei auch S drin stehen und nicht DFSroot
z.B.:
Falsch:   file:///dfsroot/Organisation/01%20Managementsystem/05%20Vorlagen%20&%20Hilfsmittel
Richtig:  file:///S:/Organisation/01%20Managementsystem/05%20Vorlagen%20&%20Hilfsmittel

Ich danke euch trz rect herzlich und ich lasse das ticket noch offen falls du noch was dazu sagen möchtest.

Grüße
Patrick
